### ISSUE TITLE
Delay when listening to the microphone

### ISSUE THREAD

**Issue by capricorn86** [mijorus/whisper#15]
Thank you for a great app that is very easy to use!

I want to use the app for hearing myself when I use my wireless headset. The headset is quite isolated and it feels weird talking when I can't hear myself.

There is a delay that makes me hear myself a little bit after. I'm not sure how much it is, but perhaps 300-500 ms. Is it any way to remove this delay?

I'm also wondering if it would be possible to add support for controlling the volume? I would just like to hear myself a little bit, but now it is a bit too load.

**Comment by mijorus** [comment]
Hi @capricorn86 ,

If you are using a wireless headset, delays have to be expected.

Whisper is already set up to open a connection (mic-speaker) with the smallest delay possible.

If you need to listen to your mic for a long time, I would suggest using a wired connection.


Volume control should be already available, if you click on the arrow you should see a slider.




Because you are not the first one reporting on this, I'm adding a warning in a future release.
